%YAML 1.2
---
SIMULATION_TIME: 500 # Simulation time in minutes
RANDOM_SEED:  42 # Radom seed
JOBS_NUMBER: 20 # Jobs number executed on each node
NODES_NUMBER: 5 # Nodes number on distributed environment
DEFAULT_REGION_SIZE: 8 # Nodes number used by default on simulation startup
CONTROLLER_FREQUENCY: 25 # Controller operating frequency
SET_POINT: 8 # The controllers set_point is the jobs number executed on each node