%YAML 1.2
---
# Simulation
SIMULATION_TIME: 500 # Simulation time in minutes
RANDOM_SEED:  42 # Radom seed
NODES_NUMBER: 5 # Nodes number on distributed environment
DEFAULT_REGION_SIZE: 8 # Nodes number used by default on simulation startup

# Controller
CONTROLLER_FREQUENCY: 25 # Controller operating frequency
SET_POINT: 8 # The controllers set_point is the jobs number executed on each node

# Disturbing
BASE_DISTURBING_PERIOD: 5 # Gap between two differents disturbings
INTERVAL_DISTURBING_PERIOD: 3 # Disturbing period variation interval
BASE_DISTURBING_LEVEL: 10 # Disturbing level initial state
INTERVAL_DISTURBING_LEVEL: 4 # Gap between two differents disturbing levels